import Head from 'next/head'
import { Linkedin, Resume, Email } from './../components/Icons'
export default function Home() {
  return (
    <div >
      <Head>
        <title>JAEL ITC</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="content container is-centered">
        <div className="brand">
          <h1 className="title">
            JAEL ITC
          </h1>
          <div className="details">
            Consulting stuff, write more information here probably
          </div>
          <div className="social">
            <a href="https://www.linkedin.com/in/aelmoussaoui/" title="LinkedIn">
              <Linkedin />
            </a>
            <a href="mailto:test@test.be" title="E-mail">
              <Email />
            </a>

            <a href="mailto:test@test.be" title="Resume">
              <Resume />
            </a>
          </div>
        </div>
      </main>
    </div>
  )
}
